import localFont from "next/font/local";
import { Arima, Arimo, DM_Serif_Display, Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import Lenis from "./_components/Lenis";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const headingSans = Arima({
  subsets: ["latin"],
  variable: "--font-headingSans",
  display: "swap",
});

const paragraphSans = Arimo({
  subsets: ["latin"],
  variable: "--font-paragraphSans",
  display: "swap",
});

export const metadata = {
  title: "BarbeX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${headingSans.variable} ${paragraphSans.variable} antialiased`}
      >
        <Lenis>
          <Header />
          <div className="lg:space-y-32 space-y-20 lg:p-0 p-6">{children}</div>
          <Footer />
        </Lenis>
      </body>
    </html>
  );
}
